### ISSUE TITLE
与sonarqube9.2.3集成后导致sonarqube启动失败。

### ISSUE THREAD

**Issue by 18552075** [donhui/sonar-mybatis#33]
2022.05.05 16:44:27 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Rule with key 'MyBatisLint:MyBatisMapperCheckRule7' not found
        at com.google.common.base.Preconditions.checkState(Preconditions.java:589)
        at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.lambda$updateOrCreateBuilder$6(BuiltInQProfileRepositoryImpl.java:203)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
        at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.updateOrCreateBuilder(BuiltInQProfileRepositoryImpl.java:200)
        at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.lambda$toQualityProfileBuilders$5(BuiltInQProfileRepositoryImpl.java:179)
        at java.base/java.util.HashMap.compute(HashMap.java:1229)
        at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.toQualityProfileBuilders(BuiltInQProfileRepositoryImpl.java:177)
        at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.lambda$toFlatList$2(BuiltInQProfileRepositoryImpl.java:135)
        at org.sonar.core.util.stream.MoreCollectors.lambda$uniqueIndex$9(MoreCollectors.java:258)
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1763)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.toFlatList(BuiltInQProfileRepositoryImpl.java:133)
        at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.initialize(BuiltInQProfileRepositoryImpl.java:87)
        at org.sonar.server.qualityprofile.BuiltInQProfileLoader.start(BuiltInQProfileLoader.java:37)

**Comment by donhui** [comment]
请使用 1.0.7 版本：https://github.com/donhui/sonar-mybatis/releases/tag/1.0.7

**Comment by 18552075** [comment]
你好，1.0.7版本验证了一下，从日志可以检查出mapper配置中的sql问题，但是sonarqube页面上报告中没有显示对应的问题。刘明伟-------- 原始邮件 --------发件人： donghui ***@***.***>日期： 2022年5月8日周日 22:07收件人： donhui/sonar-mybatis ***@***.***>抄送： 18552075 ***@***.***>, Author ***@***.***>主    题： Re: [donhui/sonar-mybatis] 与sonarqube9.2.3集成后导致sonarqube启动失败。 (Issue #33)

请使用 1.0.7 版本：https://github.com/donhui/sonar-mybatis/releases/tag/1.0.7

**Comment by donhui** [comment]
重新发布了下，版本号没变，有空再验证下

**Comment by 18552075** [comment]
你好，昨天出的版本OK了。👍刘明伟-------- 原始邮件 --------发件人： donghui ***@***.***>日期： 2022年5月13日周五 21:53收件人： donhui/sonar-mybatis ***@***.***>抄送： 18552075 ***@***.***>, Author ***@***.***>主    题： Re: [donhui/sonar-mybatis] 与sonarqube9.2.3集成后导致sonarqube启动失败。 (Issue #33)

重新发布了下，版本号没变，有空再验证下
